# Generated by Django 5.2.8 on 2025-11-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
